"""added player col

Revision ID: 174c4fac2bab
Revises: d62e36535397
Create Date: 2022-03-24 19:46:21.248645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '174c4fac2bab'
down_revision = 'd62e36535397'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('player', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_user_player'), 'user', ['player'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_player'), table_name='user')
    op.drop_column('user', 'player')
    # ### end Alembic commands ###
